### ISSUE TITLE
Introduction to Agile with GitHub

### ISSUE THREAD

**Issue by jasonb1910** [jasonb1910/sp23-cse110-lab3#1]
Doing tasks on Part 1

**Comment by jasonb1910** [comment]
# Part 1. Introduction to Agile with GitHub

Give this a quick read:[ https://github.com/features/project-management/Links to an external site.](https://github.com/features/project-management/). 
It introduces project management using different features in GitHub. More specifically, we’ll be practicing[ using Issues and Pull RequestsLinks to an external site.](https://docs.github.com/en/github/managing-your-work-on-github/managing-your-work-with-issues-and-pull-requests) in this part of the lab.

The point of this part of the lab is to introduce you to the general workflow of how your team should operate using GitHub. If done properly: everything is clearly documented for everyone on your team to see, there is a clear list of what needs to be done up next, and (theoretically) any new team member could be onboarded easily by simply looking through your repository.

## Issues
[https://guides.github.com/features/issues/Links to an external site.](https://guides.github.com/features/issues/)

- [x]  Create custom labels

- [x]  Create a custom [issue templateLinks to an external site.](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) 

- [x] Go through this week’s lab and breakdown tasks. Then create issues for those tasks with the appropriate labels and assignee (yourself).

    - Tasks can be something like: “Create meeting minutes template” or “Style meeting minutes”
 

## Pull Requests
[https://guides.github.com/activities/hello-world/#prLinks to an external site.](https://guides.github.com/activities/hello-world/#pr)

- [ ]  As you go through part 2, make incremental pull requests to resolve the issues you’ve made (ideally 1 pull request per issue)

1. Instead of pushing straight to master, create a new branch to push to. 
2. Make your changes on this branch.
3. Make a pull request from this branch to merge changes back into the main branch. Before you merge the pull request, [link this pull request to its corresponding issueLinks to an external site.](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). 
4. Repeat this process for each issue.
   
## Standup Notes
[This Agile standup guide from Atlassian](https://www.atlassian.com/agile/scrum/standups) has a good explanation of what standups are. Essentially, standups are daily meetings where typically, each member gives their status updates so that the team can keep track of sprint progress and resolve blockers. Standup notes are just notes to facilitate this meeting.

- [x]  Create a standup notes template in a Markdown file standup.md
